import random

def private_key(p):
    '''Generates a private key for the Diffie-Hellman key exchange.

    Parameters
    p: int
        A prime number generated by a test program.
    '''
    
    return random.randrange(2, p)


def public_key(p, g, private):
    '''Generates a public key for the Diffie-Hellman key exchange.

    Parameters
    p: int
        A prime number generated by the test program.
    g: int
        A prime number generated by the test program.
    private: int
        Private key generated by the private_key function.
    '''

    return pow(g, private, p)


def secret(p, public, private):
    '''Generates a secret key for the Diffie-Hellman key exchange.

    Parameters
    p: int
        A prime number generated by the test program.
    private: int
        Private key generated by the private_key function.
    public: int
        Private key generated by the public_key function.
    '''

    return pow(public, private, p)
    